import { QuestionRaw } from 'backend/interfaces';

export const questions: QuestionRaw[] = [
  //html css js
  {
    id: "123",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1231",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "122",
    statement: "functions are ",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "2121",
    statement: "css is",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },
  {
    id: "2123",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "21231",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "2122",
    statement: "functions are ",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "2521",
    statement: "css is",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },

  {
    id: "7123",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "71231",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "7122",
    statement: "functions are ",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "7121",
    statement: "css is",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },
  {
    id: "27123",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "217231",
    statement: "html is a ",
    "0": "markup language.",
    "1": "famous book.",
    "2": "turing complete language.",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "72122",
    statement: "functions are ",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "72521",
    statement: "css is",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },
];
