import { QuestionRaw } from "backend/interfaces";

export const questions: QuestionRaw[] = [
  //html css js
  {
    id: "123",
    statement: "What is html?",
    "0": "a markup language",
    "1": "a famous book",
    "2": "turing complete language",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1231",
    statement: "What is a html element?",
    "0": "elements that have no content",
    "1": "everything inside html tag",
    "2": "html tag along with its content",
    "3": "none of the above",
    correct_option: "2",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1232",
    statement: "Which is not a valid html tag?",
    "0": "header",
    "1": "footer",
    "2": "below",
    "3": "h4",
    correct_option: "2",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1233",
    statement: "Which is not a valid html tag?",
    "0": "i",
    "1": "o",
    "2": "s",
    "3": "em",
    correct_option: "1",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "1234",
    statement: "What is the full form of CSS?",
    "0": "Complete style sheets",
    "1": "Cascading style sheets",
    "2": "Coupled style sheets",
    "3": "none of the above",
    correct_option: "1",
    tags: ["CSS"],
    level: "EASY",
  },
  {
    id: "1235",
    statement: "Which of the following is untrue?",
    "0": "Javascript is an asynchronous language",
    "1": "Javascript cannot run without html",
    "2": "Javascript is a single threaded language",
    "3": "Javascript supports First class functions",
    correct_option: "1",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1236",
    statement: "What is the effect of <b> tag?",
    "0": "Changes it's content black",
    "1": "Converts it's content to bold",
    "2": "Changes content to bigger font",
    "3": "none of the above",
    correct_option: "1",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1237",
    statement:
      "Which attribute is used to provide a unique name to an HTML element?",
    "0": "class",
    "1": "type",
    "2": "id",
    "3": "all of the above",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "1238",
    statement: "Css is used for..",
    "0": "filling colors",
    "1": "is a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },

  {
    id: "1239",
    statement: "What is the correct syntax of doctype in HTML5? ",
    "0": "<!doctype html>",
    "1": "</doctype html>",
    "2": "<doctype html>",
    "3": "<doctype html!>",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "12310",
    statement: "Which element is used to get highlighted text in HTML5? ",
    "0": "<h>",
    "1": "<u>",
    "2": "<mark>",
    "3": "<highlight>",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12311",
    statement: "Functions are",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12312",
    statement: "Which of the following is not a HTML5 tag?",
    "0": "<source>",
    "1": "<video>",
    "2": "<slider>",
    "3": "<track>",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12313",
    statement:
      "Which of the following is not the element associated with the HTML table layout?",
    "0": "alignment",
    "1": "spanning",
    "2": "color",
    "3": "size",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12314",
    statement: " HTML is a subset of..",
    "0": "SGME",
    "1": "XHTML",
    "2": "SGML",
    "3": "SGMT",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12315",
    statement: "Which HTML element is used for short quote?",
    "0": "<blockquote>",
    "1": "<abbr>",
    "2": "<em>",
    "3": "<q>",
    correct_option: "3",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12316",
    statement: "css is..",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },
  {
    id: "12317",
    statement: "Apart from <b> tag, what other tag can make text bold?",
    "0": "<strong>",
    "1": "<black>",
    "2": "<emp>",
    "3": "<fat>",
    correct_option: "0",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12318",
    statement:
      "Which ____ attribute specifies where to open the linked document?",
    "0": "src",
    "1": "link",
    "2": "target",
    "3": "href",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12319",
    statement: "Which tag is used to define description lists?",
    "0": "<check> ... </check>",
    "1": "<dd> ... </dd>",
    "2": "<dlist> ... </dlist>",
    "3": "<dl> ... </dl>",
    correct_option: "3",
    tags: ["HTML"],
    level: "HARD",
  },

  {
    id: "12320",
    statement: "Which tag specifies an inline frame?",
    "0": "<frame>",
    "1": "<iframe>",
    "2": "<ilFrames>",
    "3": "<inlineframe>",
    correct_option: "1",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12321",
    statement: "What are the best examples of void elements?",
    "0": "<link><meta><title>",
    "1": "<input><br><p>",
    "2": "<br><base><source>",
    "3": "<area><embed><strong>",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12322",
    statement: 'The "value" attribute is associated with which set of tags?',
    "0": "<button><input><form>",
    "1": "<input><label><meter>",
    "2": "<li><input><option>",
    "3": "<input><option><textarea>",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12323",
    statement: "Which of the following is not block-scoped?",
    "0": "Let",
    "1": "var",
    "2": "const",
    "3": "None of the above",
    correct_option: "1",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12324",
    statement: "Which of the following is not a way to access a Html element?",
    "0": "getElementById()",
    "1": "getElementsByClassName()",
    "2": "getElementByValue()",
    "3": "querySelectorAll()",
    correct_option: "2",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12325",
    statement: "What will this output- console.log(a = 5 + '9')",
    "0": "14",
    "1": "will result in error",
    "2": "12",
    "3": "59",
    correct_option: "3",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12326",
    statement: 'For var a = "Scaler"; a.substring(2, 4) will output?  ',
    "0": "al",
    "1": "ale",
    "2": "caler",
    "3": "cal",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12327",
    statement: "What is the use of the <noscript> tag in Javascript?",
    "0": "Prevents the script from running",
    "1": "The contents are displayed by non-js-based browsers only",
    "2": "Clears all cookies and caches",
    "3": "None of the above",
    correct_option: "1",
    tags: ["JS"],
    level: "MED",
  },
  {
    id: "12328",
    statement: 'The "function" and " var" are..',
    "0": "Declaration statements",
    "1": "Keywords",
    "2": "Data types",
    "3": "Prototypes",
    correct_option: "1",
    tags: ["JS"],
    level: "MED",
  },

  {
    id: "12329",
    statement: "Which of the following scoping type does JavaScript use?",
    "0": "Literal",
    "1": "Sequential",
    "2": "Segmental",
    "3": "Lexical",
    correct_option: "3",
    tags: ["JS"],
    level: "MED",
  },

  {
    id: "12330",
    statement: "What is concat used for",
    "0": "to merge two arrays",
    "1": "to create new array",
    "2": "to delete the concurrent elements",
    "3": "None of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "MED",
  },

  {
    id: "12331",
    statement: "What will this output- console.log(isNaN(false))",
    "0": "true",
    "1": "error",
    "2": "false",
    "3": "None of the above",
    correct_option: "2",
    tags: ["JS"],
    level: "MED",
  },
  {
    id: "12332",
    statement: "How is multi-line comments added in JS",
    "0": "## and ##",
    "1": "<!—and -->",
    "2": "// and //",
    "3": "None of the above",
    correct_option: "3",
    tags: ["JS"],
    level: "HARD",
  },
  {
    id: "12332",
    statement: "How many keywords are there in Js to declare variables?",
    "0": "One",
    "1": "Two",
    "2": "Three",
    "3": "Four",
    correct_option: "2",
    tags: ["JS"],
    level: "HARD",
  },
  {
    id: "12334",
    statement: "What is the default value of an uninitialized variable?",
    "0": "0",
    "1": "undefined",
    "2": "null",
    "3": "NaN",
    correct_option: "1",
    tags: ["JS"],
    level: "HARD",
  },
  {
    id: "12335s",
    statement: "Which is the exponentiation operator in JavaScript?",
    "0": "Math.pow()",
    "1": "exp()",
    "2": "^",
    "3": "**",
    correct_option: "3",
    tags: ["JS"],
    level: "HARD",
  },
  {
    id: "12335s",
    statement: "Output- let ac = [1,2,3,4];for(i in ac ){console.log(i)}",
    "0": "4",
    "1": "3",
    "2": '"3"',
    "3": "None of the above",
    correct_option: "2",
    tags: ["JS"],
    level: "HARD",
  },
];
