import { QuestionRaw } from "backend/interfaces";

export const questions: QuestionRaw[] = [
  //html css js
  {
    id: "123",
    statement: "What is html?",
    "0": "a markup language",
    "1": "a famous book",
    "2": "turing complete language",
    "3": "none of the above",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1231",
    statement: "What is a html element?",
    "0": "elements that have no content",
    "1": "everything inside html tag",
    "2": "html tag along with its content",
    "3": "none of the above",
    correct_option: "2",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1232",
    statement: "Which is not a valid html tag?",
    "0": "header",
    "1": "footer",
    "2": "below",
    "3": "h4",
    correct_option: "2",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1233",
    statement: "Which is not a valid html tag?",
    "0": "i",
    "1": "o",
    "2": "s",
    "3": "em",
    correct_option: "1",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "1234",
    statement: "What is the full form of CSS?",
    "0": "Complete style sheets",
    "1": "Cascading style sheets",
    "2": "Coupled style sheets",
    "3": "none of the above",
    correct_option: "1",
    tags: ["CSS"],
    level: "EASY",
  },
  {
    id: "1235",
    statement: "Which of the following is untrue?",
    "0": "Javascript is an asynchronous language",
    "1": "Javascript cannot run without html",
    "2": "Javascript is a single threaded language",
    "3": "Javascript supports First class functions",
    correct_option: "1",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1236",
    statement: "What is the effect of <b> tag?",
    "0": "Changes it's content black",
    "1": "Converts it's content to bold",
    "2": "Changes content to bigger font",
    "3": "none of the above",
    correct_option: "1",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "1237",
    statement:
      "Which attribute is used to provide a unique name to an HTML element?",
    "0": "class",
    "1": "type",
    "2": "id",
    "3": "all of the above",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "1238",
    statement: "Css is used for..",
    "0": "filling colors",
    "1": "is a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },

  {
    id: "1239",
    statement: "What is the correct syntax of doctype in HTML5? ",
    "0": "<!doctype html>",
    "1": "</doctype html>",
    "2": "<doctype html>",
    "3": "<doctype html!>",
    correct_option: "0",
    tags: ["HTML"],
    level: "EASY",
  },
  {
    id: "12310",
    statement: "Which element is used to get highlighted text in HTML5? ",
    "0": "<h>",
    "1": "<u>",
    "2": "<mark>",
    "3": "<highlight>",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12311",
    statement: "Functions are",
    "0": "first class citizens in javascript",
    "1": "not objects",
    "2": "similar to arrays",
    "3": "all of the above",
    correct_option: "0",
    tags: ["JS"],
    level: "EASY",
  },
  {
    id: "12312",
    statement: "Which of the following is not a HTML5 tag?",
    "0": "<source>",
    "1": "<video>",
    "2": "<slider>",
    "3": "<track>",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12313",
    statement:
      "Which of the following is not the element associated with the HTML table layout?",
    "0": "alignment",
    "1": "spanning",
    "2": "color",
    "3": "size",
    correct_option: "2",
    tags: ["HTML"],
    level: "MED",
  },
  {
    id: "12314",
    statement: " HTML is a subset of..",
    "0": "SGME",
    "1": "XHTML",
    "2": "SGML",
    "3": "SGMT",
    correct_option: "2",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12315",
    statement: "Which HTML element is used for short quote?",
    "0": "<blockquote>",
    "1": "<abbr>",
    "2": "<em>",
    "3": "<q>",
    correct_option: "3",
    tags: ["HTML"],
    level: "HARD",
  },
  {
    id: "12316",
    statement: "css is..",
    "0": "just used for filling colors",
    "1": "a markup language",
    "2": "an alternative to javascript",
    "3": "none of the above",
    correct_option: "3",
    tags: ["CSS"],
    level: "EASY",
  },
];
