import { UserRaw } from "backend/interfaces";

import { getCurrentDateTime } from "../utils";

export const users: UserRaw[] = [
  {
    id: "666",
    fname: "Surbhi",
    lname: "Kukreti",
    username: "Surbhikukreti99",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "randoms@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 70,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 70,
    incorrectAnswered: 30,
    role: "ADMIN",
  },
  {
    id: "661",
    fname: "Raj",
    lname: "Verma",
    username: "RajV",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "rajv@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 60,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 60,
    incorrectAnswered: 40,
    role: "ADMIN",
  },
  {
    id: "611",
    fname: "Rajlaxmi",
    lname: "Verma",
    username: "rlax",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "rlax@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 50,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 50,
    incorrectAnswered: 50,
    role: "PLAYER",
  },
  {
    id: "6155",
    fname: "Shweta",
    lname: "Sharma",
    username: "shws",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "shws@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 45,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 45,
    incorrectAnswered: 55,
    role: "PLAYER",
  },
  {
    id: "68855",
    fname: "Vikram",
    lname: "Sharma",
    username: "vks",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "vks@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 43,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 43,
    incorrectAnswered: 57,
    role: "PLAYER",
  },
  {
    id: "78855",
    fname: "Dhruv",
    lname: "Sharma",
    username: "drvs",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "drvs@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 42,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 42,
    incorrectAnswered: 58,
    role: "PLAYER",
  },
  {
    id: "788535",
    fname: "Deepak",
    lname: "Sharma",
    username: "deep",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "deep@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 41,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 41,
    incorrectAnswered: 59,
    role: "PLAYER",
  },
  {
    id: "568535",
    fname: "Shivang",
    lname: "Sharma",
    username: "Shiv",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "Shiv@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 40,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 40,
    incorrectAnswered: 60,
    role: "PLAYER",
  },
  {
    id: "1168535",
    fname: "Shivangi",
    lname: "Sharma",
    username: "Shivi",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "Shivi@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 30,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 30,
    incorrectAnswered: 70,
    role: "PLAYER",
  },
  {
    id: "1368535",
    fname: "Arun",
    lname: "Sharma",
    username: "Aru",
    password: "acheDin",
    dob: "1997-03-07",
    contact: 8057700000,
    email: "Aru@gmail.com",
    createdAt: getCurrentDateTime(),
    updatedAt: getCurrentDateTime(),
    score: 20,
    quizPlayed: 10,
    recentlyPlayed: [
      { categoryId: "11", level: "EASY" },
      { categoryId: "11", level: "MID" },
      { categoryId: "11", level: "HARD" },
    ],
    correctAnswered: 20,
    incorrectAnswered: 80,
    role: "PLAYER",
  },
];
